In [1]:
import numpy as np
import time

# NumPy vs. Python Lists – Performance Test
Let's compare Python lists with NumPy arrays using a simple example.

In [2]:
# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)

Python list addition time: 0.049262285232543945
NumPy array addition time: 0.01821589469909668


# Creating NumPy Arrays

In [3]:
# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape of arr1: (5,)
Shape of arr2: (2, 3)


# Memory Efficiency – NumPy vs. Lists

In [4]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


# Vectorization – No More Loops!
NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.

In [5]:
size=1_000_000_00
list1=list(range(size))
start=time.time()
list_square=[x**2 for x in list1]
end=time.time()
print(f"The square of list1: {list_square [0:20]}")
print(f"Time taken: {end-start}")

The square of list1: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
Time taken: 5.8407227993011475


In [6]:
arr1= np.array(list1)
start=time.time()
numpy_square=arr1**2
end=time.time()
print(f"The square of list1: {list_square [0:20]}")
print(f"Time taken: {end-start}")

The square of list1: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
Time taken: 0.5786271095275879
